### ISSUE TITLE
Directory em_narration_clip_token_features and nlq_v2_clip_token_features not found

### ISSUE THREAD

**Issue by ayiyayi** [houzhijian/GroundNLQ#4]
Hi!
Thanks for your code sharing. I met some error when using ` bash tools/pretrain_ego4d_narration.sh CONFIG_FILE OUTPUT_PATH `, could yout please tell me how to get directory em_narration_clip_token_features and nlq_v2_clip_token_features?
Thank you every much. ^_^

**Comment by houzhijian** [comment]
Hi, ayiyayi:

Thanks for your interest. I uploaded further data, which includes textual token features. You can download it at https://drive.google.com/file/d/1tyrVLcs0m0svA6TZpubX_VlpjAvLU18F/view?usp=sharing.
